name = "edge-tracker"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-04-10"

[build]
command = "npm install && npm test && npm run build"
[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{name = "TORRENT", class_name = "Torrent"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Torrent"]
